### ISSUE TITLE
Library overrides native window onscroll function and does not clean up

### ISSUE THREAD

**Issue by lifenautjoe** [caiofsouza/vue-backtotop#4]
# Library overrides native window onscroll

The library overrides the native handler for onscroll by doing 

````js
    window.onscroll = catchScroll;
````

This means, no other events can be attached to the window scrolling apart from the library one.

The way to do it properly is with

````js
 window.addEventListener('scroll', catchScroll);
````

This is not supported on IE8 and below but in the year 2018, it's no longer an issue.

# Library does not clean up

The library should remove all event listeners when the element is destroyed, otherwise its always in memory, consuming resources. 

Given the first problem solution this should be done on the Vue destroy lifecycle hook like this

````js

destroyed(){
    window.removeEventListener('scroll', catchScroll);
}

````

**Comment by caiofsouza** [comment]
Hey @lifenautjoe,

This was a mistake, and will be fixed on next version :D

Thanks !
