### ISSUE TITLE
Attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates

### ISSUE THREAD

**Issue by botmaster** [caiofsouza/vue-backtotop#5]
Prop "visibleoffset" is passed to component BackToTop, but the declared prop name is "visibleOffset". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates.
You should probably use "visible-offset" instead of "visibleOffset".

**Comment by caiofsouza** [comment]
Hey @botmaster,

Of course, the name of props and the passed attributes are different, and I'll change that on the next version,

Thanks for you suggestion
