### ISSUE TITLE
Provide a dist javascript file of this library

### ISSUE THREAD

**Issue by tno2007** [caiofsouza/vue-backtotop#6]
Could you please provide a dist javascript file of this library for use when you simply want to link a javascript file in a html page.

For example:
    <script src="vue-backtotop.js"></script>

I understand that everything is moving to npm and will be more optimised that way, but some of us still prefer development without a build system like webpack.

Thanks

**Comment by caiofsouza** [comment]
Hi @tno2007, 

Honestly, I don't think about that, but I can upload the dist file to any cdn,

Thanks !
